### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by SET001** [eyalsk-solutions/TypeScript-RequireJS-And-Karma#2]
I can't understand how this suppose to work with this configuration...
in `src/tests/core/object.tests.ts` you have

define(["framework/core/object"], () =>

but framework folder is 2 layers up from this current file, so it should be `define(["../../framework/core/object"], () =>` otherwise typescript compiler will  throw error about that it cant found such module.

**Comment by eyalsk** [comment]
No, it's working correctly simply because requirejs resolves the paths from '/base/src', it's very long time since I've touched this but I've doubled checked that and it works perfectly fine, all the tests are passing, you need to look at tests/test.main.js

**Comment by eyalsk** [comment]
Fixed, thanks!
